version: '2'

services:

  eureka:
    image: springcloud/eureka
    ports:
      - '8761:8761'

  mongo:
    image: mongo:3.6
    ports:
      - '27017:27017'

  pc:
    build: pc/
    ports:
      - '8081:8080'
      - '5010:5005'
    depends_on:
      - eureka
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'

  po:
    build: po/
    ports:
      - '8082:8080'
      - '5020:5005'
    links:
      - pc
    depends_on:
      - eureka
      - mongo
      - pc
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      pcurl: 'pc:8080'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'
      FEIGN_HYSTRIX_ENABLED: 'true'

  zuul-server:
    build: zuul-server/
    ports:
      - '5016:5006'
      - '8762:8762'
    depends_on:
      - eureka
      - po
      - pc
    links:
      - eureka:eureka
    environment:
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: '*'

  auth-service:
    build: auth-service/
    ports:
      - '5017:5006'
      - '8888:8080'
    depends_on:
      - eureka
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'

  elasticsearch:
    image: elasticsearch:5.5.0
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'

  logstash:
    image: logstash:5.5.0
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - '5000:5000'
    links:
      - elasticsearch

  kibana:
    image: kibana:5.5.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - '5601:5601'
    links:
      - elasticsearch

networks:
    default:
        driver: bridge
